/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.marcelorar.software.tata.balancemanager.api;

import org.springframework.format.annotation.DateTimeFormat;
import com.marcelorar.software.tata.balancemanager.model.GetTransactionsByDateByClient200ResponseInner;
import java.time.LocalDate;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-06-28T04:18:04.104925500-05:00[America/Guayaquil]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Transaction", description = "Operations related to transactions committed to Accounts.")
public interface ReportesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /reportes/{clientId} : Get Transactions filtered by date and client.
     * Get Transactions filtered by date and client.
     *
     * @param clientId Client to be queried. (required)
     * @param pgSize The amount of transactions per page. (required)
     * @param pg The page for the bulk of transactions. (required)
     * @param startDate Start Date of the query. (required)
     * @param endDate Last Date of the query. (required)
     * @return Query Successfully Executed (status code 200)
     */
    @Operation(
        operationId = "getTransactionsByDateByClient",
        summary = "Get Transactions filtered by date and client.",
        description = "Get Transactions filtered by date and client.",
        tags = { "Transaction" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Query Successfully Executed", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = GetTransactionsByDateByClient200ResponseInner.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/reportes/{clientId}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<GetTransactionsByDateByClient200ResponseInner>> getTransactionsByDateByClient(
        @Parameter(name = "clientId", description = "Client to be queried.", required = true, in = ParameterIn.PATH) @PathVariable("clientId") Integer clientId,
        @NotNull @Parameter(name = "pgSize", description = "The amount of transactions per page.", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "pgSize", required = true) Integer pgSize,
        @NotNull @Parameter(name = "pg", description = "The page for the bulk of transactions.", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "pg", required = true) Integer pg,
        @NotNull @Parameter(name = "startDate", description = "Start Date of the query.", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "startDate", required = true) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate startDate,
        @NotNull @Parameter(name = "endDate", description = "Last Date of the query.", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "endDate", required = true) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate endDate
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"date\" : \"2024-06-13T19:19:56Z\", \"lastBalance\" : \"100.23\", \"issuedAmount\" : \"100.23\", \"accountType\" : \"SAVINGS\", \"currentBalance\" : \"100.23\", \"name\" : \"Carlos Garcia\", \"operation\" : \"DEBIT\", \"account\" : \"200012\" }, { \"date\" : \"2024-06-13T19:19:56Z\", \"lastBalance\" : \"100.23\", \"issuedAmount\" : \"100.23\", \"accountType\" : \"SAVINGS\", \"currentBalance\" : \"100.23\", \"name\" : \"Carlos Garcia\", \"operation\" : \"DEBIT\", \"account\" : \"200012\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
